### ISSUE TITLE
begin() erases accumulation registers

### ISSUE THREAD

**Issue by marcobergman** [adafruit/Adafruit_INA228#7]
In applications where the INA228 is interfaced with an ESP8266, the latter might be put in sleep mode, only to be awakened by the alert function of the INA228. In that case, the INA228 should not be reset at power-up, especially not the accumulation registers ENERGY and CHARGE. Currently the Adafruit INA228 library resets both configuration and accumulation registers at initialisation time (RST and RSTACC), thereby typically 'erasing the SOC information of a battery'.

To solve this, the following amendments should be made:
* Allow initialisation without calling reset(). For instance, by adding an optional boolean parameter to begin().

Furthermore, an SOC-calculating application might at some point want to reset the accumulation registers ENERGY and CHARGE (by setting RSTACC). The current reset function does both RST and RSTACC.
* Please splits the reset() function into two functions: resetConfig() and resetAcc(). The original reset() function might call them both for backward compatibility purposes.

**Comment by ladyada** [comment]
check the latest commit, you can now skip reset!
