### ISSUE TITLE
Incorrect result from readDieTemp()

### ISSUE THREAD

**Issue by donmsmall** [adafruit/Adafruit_INA228#8]
Temps below zero are showing very large positive values.

![Screenshot 2024-02-13 083520](https://github.com/adafruit/Adafruit_INA228/assets/159927469/9ab67e3a-bc98-49cc-b190-19b95b843e60)

This is the current function.
float Adafruit_INA228::readDieTemp(void) {
  Adafruit_I2CRegister temp =
      Adafruit_I2CRegister(i2c_dev, INA228_REG_DIETEMP, 2, MSBFIRST);
  return (float)temp.read() * 7.8125f / 1000.0f;
}

Resolved by placing the 2 bytes read from the INA228 register into a int16_t variable.
float Adafruit_INA228::readDieTemp(void) {
  Adafruit_I2CRegister temp =
      Adafruit_I2CRegister(i2c_dev, INA228_REG_DIETEMP, 2, MSBFIRST);
  int16_t t = temp.read();
  return (float)t * 7.8125f / 1000.0f;
}

**Comment by ladyada** [comment]
thanks, commited a fix!
